### ISSUE TITLE
TypeError is thrown when attempting to post to mediawiki

### ISSUE THREAD

**Issue by ghost** [oliver-moran/mediawiki#5]
When I try this:

``` javascript
var MediaWiki = require('mediawiki');

var bot = new MediaWiki.Bot({
    endpoint: "https://en.wikipedia.org/w/api.php",
    rate: 60e3 / 10,
    userAgent: "ExampleBot <https://en.wiktionary.org/wiki/User:Example>",
    byeline: "(example bot edit)"
});

bot.login('my_username', 'my_password').complete(function (username) {
    console.log(['Username:', username].join(' '));

    bot.edit('User:My_Page', 'Testing via API', 'This is a test.')
        .complete(function (title, revision, date) {
            console.log(title);
            console.log(revision);
            console.log(date.toString());
        }).error(function (err) {
            console.log('Error');
            console.log(err); 
        });
});
```

I get this:

```
TypeError: Cannot read property 'result' of undefined
    at Bot.<anonymous> (/home/username/src/exercises/mediawiki_api/node_modules/mediawiki/mediawiki.js:485:34)
    at Bot._processResponse (/home/username/src/exercises/mediawiki_api/node_modules/mediawiki/mediawiki.js:227:29)
    at Request._callback (/home/username/src/exercises/mediawiki_api/node_modules/mediawiki/mediawiki.js:179:34)
    at Request.self.callback (/home/username/src/exercises/mediawiki_api/node_modules/mediawiki/node_modules/request/request.js:121:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/home/username/src/exercises/mediawiki_api/node_modules/mediawiki/node_modules/request/request.js:978:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/home/username/src/exercises/mediawiki_api/node_modules/mediawiki/node_modules/request/request.js:929:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
```

When I `console.log` the data variable on line 484 of mediawiki.js, I get:

```
Username: my_username
{ servedby: 'mw1189',
  error: 
   { code: 'mustposttoken',
     info: 'The \'token\' parameter was found in the query string, but must be in the POST body',
     '*': 'See https://en.wikipedia.org/w/api.php for API usage' } }
```

**Comment by brettz9** [comment]
I'm looking to possibly address this issue and/or add some enhancements, but was wondering if you were still maintaining the repo, @oliver-moran ?

**Comment by brettz9** [comment]
Also, @oliver-moran , are you set on using the GPL or would you be open to a more permissive type like MIT?
